name: xylophone
description: "A music app that plays Xylophone sounds."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  assets_audio_player: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
  fonts:
    - family: Neucha
      fonts:
        - asset: assets/fonts/Neucha-Regular.ttf

